services:
  gestionguiasdespacho:
    build:
      context: .
      dockerfile: Dockerfile

    image: gestionguiasdespacho:latest
    container_name: gestion-guias-despacho

    ports:
      - "8081:8081"

    env_file:
      - .env

    volumes:
      - "/home/natalia/Archivos/Desarrollo Cloud Native/Wallets Registradas/Wallet_Semana3:/home/natalia/wallets/wallet3:ro"
      - "./guias:/mnt/efs/guias"

    restart: "no"