services:

  gestionguiasdespacho:
    build:
      context: .
      dockerfile: Dockerfile

    image: ladyred/gestionguiasdespacho:latest
    container_name: gestion-guias-despacho

    ports:
      - "8081:8081"

    env_file:
      - .env

    environment:
      SERVER_PORT: 8081

      JAVA_TOOL_OPTIONS: "-Doracle.jdbc.javaNetNio=false"

      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guias_app}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guias_app_local}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST:-/}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - "/home/natalia/Archivos/Desarrollo Cloud Native/Wallets Registradas/Wallet_Semana3:/home/natalia/wallets/wallet3:ro"
      - "./guias:/mnt/efs/guias"

    restart: "no"
