services:
  gestionguiasdespacho:
    image: ladyred/gestionguiasdespacho:latest
    container_name: Semana3

    ports:
      - "8081:8080"

    env_file:
      - .env

    volumes:
      - "/home/natalia/wallets/Wallet_Semana3:/app/wallet:ro"
      - "./guias:/mnt/efs/guias"

    restart: "no"