# APP
spring.application.name=gestionguiasdespacho
spring.config.import=optional:file:.env[.properties]
server.port=8081

# ORACLE CLOUD DATABASE - WALLET
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# AWS S3
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:gestion-guias-despacho-grupo13}

# EFS - ALMACENAMIENTO TEMPORAL
app.efs.base-path=${EFS_BASE_PATH:/mnt/efs/guias}

# AZURE AD B2C / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWK_SET_URI:}

# SWAGGER / OPENAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ERROR HANDLING
server.error.include-message=always
server.error.include-binding-errors=always